add_newline = false

[line_break]
disabled = true

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user](red bold)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "[$user](bold red)@[$hostname](bold red) "
disabled = false

[character]
# success_symbol = "[λ](bold green)"
# error_symbol = "[λ](bold red)"

success_symbol = "[→](bold green)"
error_symbol = "[→](bold red)"
vicmd_symbol = "[←](bold blue)"

