add_newline = false

[line_break]
disabled = true

[character]
# success_symbol = "[λ](bold green)"
# error_symbol = "[λ](bold red)"

success_symbol = "[→](bold green)"
error_symbol = "[→](bold red)"
vicmd_symbol = "[←](bold blue)"
