add_newline = false

[line_break]
disabled = true

#[username]
#style_user = "white bold"
#style_root = "black bold"
#format = "[$user](blue bold)"
#disabled = false
#show_always = true

#[hostname]
#ssh_only = false
#format = "[$user](blue bold)@[$hostname](green bold) "
#disabled = false

[character]
# success_symbol = "[❯](bold green)"
# error_symbol = "[❯](bold red)"
# vicmd_symbol = "[❮](bold magenta)"

success_symbol = "[λ](bold green)"
error_symbol = "[λ](bold red)"
vicmd_symbol = "[λ](bold magenta)"

# success_symbol = "[→](bold blue)"
# error_symbol = "[→](bold red)"
# vicmd_symbol = "[←](bold yellow)"
